### ISSUE TITLE
Ensure express and node headers are turned off

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/PET-Template#4]
I'm unsure whether this is a problem, as I'm out and about right now, but it would be wise to make sure that packet headers that would expose any type of data about how our backend is structured should be hidden

**Comment by crutchcorn** [comment]
This issue is fixed under the config branch, but I am holding to merge until I can solve the issues in that branch

**Comment by crutchcorn** [comment]
Closing as the fix is in config branch, which is 99% ready for merging

**Comment by sagarppatil** [comment]
Sorry to barge in. I just wanted to say that I loved the structure that you have in this repo. 

Also, I realize this comment is closed but have you looked at HelmetJS (https://helmetjs.github.io/). It should be able to solve most of your header related issues and add some more hardening to your server.

Thanks again for the wonderful work.

**Comment by crutchcorn** [comment]
@sagarppatil Thank you so much for your kind words! It makes me more encouraged to continue work on this project. :)

I'm actually using Lusca and Helmet in the project in the `auth` branch (which will become master hopefully this week). You can see the code here: 
https://github.com/crutchcorn/PET-Template/blob/auth/src/config/lib/express.ts
